// Comprehensive list of world currencies with their symbols and countries
const currencies = [
    { code: 'USD', symbol: '$', name: 'US Dollar', country: 'United States' },
    { code: 'EUR', symbol: '€', name: 'Euro', country: 'European Union' },
    { code: 'GBP', symbol: '£', name: 'British Pound', country: 'United Kingdom' },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen', country: 'Japan' },
    { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', country: 'Australia' },
    { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', country: 'Canada' },
    { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', country: 'Switzerland' },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', country: 'China' },
    { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', country: 'Sweden' },
    { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', country: 'New Zealand' },
    
    // Africa
    { code: 'ZAR', symbol: 'R', name: 'South African Rand', country: 'South Africa' },
    { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', country: 'Nigeria' },
    { code: 'EGP', symbol: '£', name: 'Egyptian Pound', country: 'Egypt' },
    { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', country: 'Kenya' },
    { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', country: 'Ghana' },
    { code: 'MAD', symbol: 'DH', name: 'Moroccan Dirham', country: 'Morocco' },
    { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', country: 'Tunisia' },
    { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', country: 'Uganda' },
    { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', country: 'Ethiopia' },
    { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'West Africa' },
    { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Central Africa' },
    { code: 'BWP', symbol: 'P', name: 'Botswana Pula', country: 'Botswana' },
    { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', country: 'Mozambique' },
    { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', country: 'Zambia' },
    
    // Asia
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', country: 'India' },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won', country: 'South Korea' },
    { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', country: 'Singapore' },
    { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', country: 'Hong Kong' },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', country: 'Malaysia' },
    { code: 'THB', symbol: '฿', name: 'Thai Baht', country: 'Thailand' },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', country: 'Indonesia' },
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso', country: 'Philippines' },
    { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', country: 'Vietnam' },
    { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar', country: 'Taiwan' },
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', country: 'Pakistan' },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', country: 'Bangladesh' },
    { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
    { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', country: 'Nepal' },
    { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', country: 'Myanmar' },
    { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', country: 'Cambodia' },
    { code: 'LAK', symbol: '₭', name: 'Lao Kip', country: 'Laos' },
    { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', country: 'Brunei' },
    
    // Middle East
    { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', country: 'United Arab Emirates' },
    { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', country: 'Saudi Arabia' },
    { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', country: 'Qatar' },
    { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', country: 'Kuwait' },
    { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', country: 'Bahrain' },
    { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', country: 'Oman' },
    { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', country: 'Israel' },
    { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', country: 'Jordan' },
    { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', country: 'Lebanon' },
    { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', country: 'Iran' },
    { code: 'IQD', symbol: 'د.ع', name: 'Iraqi Dinar', country: 'Iraq' },
    
    // Europe
    { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', country: 'Norway' },
    { code: 'DKK', symbol: 'kr', name: 'Danish Krone', country: 'Denmark' },
    { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', country: 'Poland' },
    { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', country: 'Czech Republic' },
    { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', country: 'Hungary' },
    { code: 'RON', symbol: 'lei', name: 'Romanian Leu', country: 'Romania' },
    { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', country: 'Bulgaria' },
    { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', country: 'Croatia' },
    { code: 'RSD', symbol: 'дин', name: 'Serbian Dinar', country: 'Serbia' },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble', country: 'Russia' },
    { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', country: 'Ukraine' },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira', country: 'Turkey' },
    { code: 'ISK', symbol: 'kr', name: 'Icelandic Krona', country: 'Iceland' },
    
    // Americas
    { code: 'MXN', symbol: '$', name: 'Mexican Peso', country: 'Mexico' },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', country: 'Brazil' },
    { code: 'ARS', symbol: '$', name: 'Argentine Peso', country: 'Argentina' },
    { code: 'CLP', symbol: '$', name: 'Chilean Peso', country: 'Chile' },
    { code: 'COP', symbol: '$', name: 'Colombian Peso', country: 'Colombia' },
    { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', country: 'Peru' },
    { code: 'VEF', symbol: 'Bs', name: 'Venezuelan Bolívar', country: 'Venezuela' },
    { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', country: 'Uruguay' },
    { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', country: 'Paraguay' },
    { code: 'BOB', symbol: 'Bs', name: 'Bolivian Boliviano', country: 'Bolivia' },
    { code: 'ECU', symbol: '$', name: 'US Dollar (Ecuador)', country: 'Ecuador' },
    { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', country: 'Guatemala' },
    { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', country: 'Honduras' },
    { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', country: 'Nicaragua' },
    { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', country: 'Costa Rica' },
    { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', country: 'Panama' },
    { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', country: 'Dominican Republic' },
    { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', country: 'Jamaica' },
    { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', country: 'Haiti' },
    { code: 'CUP', symbol: '$', name: 'Cuban Peso', country: 'Cuba' },
    { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', country: 'Barbados' },
    { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago' },
    
    // Oceania
    { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', country: 'Fiji' },
    { code: 'PGK', symbol: 'K', name: 'Papua New Guinea Kina', country: 'Papua New Guinea' },
    { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', country: 'Tonga' },
    { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', country: 'Samoa' },
    { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', country: 'Vanuatu' },
    { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', country: 'Solomon Islands' },
    
    // Additional Asian currencies
    { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', country: 'Afghanistan' },
    { code: 'AMD', symbol: '֏', name: 'Armenian Dram', country: 'Armenia' },
    { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', country: 'Azerbaijan' },
    { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', country: 'Belarus' },
    { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', country: 'Bhutan' },
    { code: 'GEL', symbol: '₾', name: 'Georgian Lari', country: 'Georgia' },
    { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', country: 'Kazakhstan' },
    { code: 'KGS', symbol: 'лв', name: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
    { code: 'MDL', symbol: 'lei', name: 'Moldovan Leu', country: 'Moldova' },
    { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', country: 'Mongolia' },
    { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', country: 'Tajikistan' },
    { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', country: 'Turkmenistan' },
    { code: 'UZS', symbol: 'лв', name: 'Uzbekistani Som', country: 'Uzbekistan' },
    
    // Additional African currencies
    { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', country: 'Algeria' },
    { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', country: 'Angola' },
    { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', country: 'Burundi' },
    { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo', country: 'Cape Verde' },
    { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', country: 'Comoros' },
    { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', country: 'Democratic Republic of Congo' },
    { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', country: 'Djibouti' },
    { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', country: 'Eritrea' },
    { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', country: 'Eswatini' },
    { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', country: 'Gambia' },
    { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', country: 'Guinea' },
    { code: 'GWP', symbol: 'CFA', name: 'Guinea-Bissau Peso', country: 'Guinea-Bissau' },
    { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', country: 'Liberia' },
    { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', country: 'Libya' },
    { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', country: 'Madagascar' },
    { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', country: 'Malawi' },
    { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', country: 'Mauritania' },
    { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', country: 'Mauritius' },
    { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', country: 'Namibia' },
    { code: 'RWF', symbol: 'RF', name: 'Rwandan Franc', country: 'Rwanda' },
    { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', country: 'São Tomé and Príncipe' },
    { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', country: 'Seychelles' },
    { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', country: 'Sierra Leone' },
    { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', country: 'Somalia' },
    { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', country: 'South Sudan' },
    { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', country: 'Sudan' },
    { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', country: 'Tanzania' },
    
    // Additional European currencies
    { code: 'ALL', symbol: 'L', name: 'Albanian Lek', country: 'Albania' },
    { code: 'BAM', symbol: 'KM', name: 'Bosnia and Herzegovina Convertible Mark', country: 'Bosnia and Herzegovina' },
    { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', country: 'North Macedonia' },
    
    // Pacific currencies
    { code: 'XPF', symbol: '₣', name: 'CFP Franc', country: 'French Polynesia' },
    { code: 'NCL', symbol: '₣', name: 'New Caledonian Franc', country: 'New Caledonia' },
    
    // Special currencies
    { code: 'XDR', symbol: 'SDR', name: 'Special Drawing Rights', country: 'International Monetary Fund' },
    { code: 'XAU', symbol: 'Au', name: 'Gold (troy ounce)', country: 'Precious Metal' },
    { code: 'XAG', symbol: 'Ag', name: 'Silver (troy ounce)', country: 'Precious Metal' },
    
    // Cryptocurrency (for modern expense tracking)
    { code: 'BTC', symbol: '₿', name: 'Bitcoin', country: 'Cryptocurrency' },
    { code: 'ETH', symbol: 'Ξ', name: 'Ethereum', country: 'Cryptocurrency' }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = currencies;
}
